name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, clippy
    - name: Check code format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Run benchmarks
      run: cargo bench --verbose
    - name: Build docs
      run: cargo doc --verbose
